# Generated by Django 5.2.4 on 2025-07-29 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrow',
            options={},
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='is_returned',
        ),
        migrations.AddField(
            model_name='borrow',
            name='borrowed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='borrow',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
