# Generated by Django 5.2.4 on 2025-07-29 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_module', '0010_book_description'),
        ('borrow_module', '0002_alter_borrow_options_remove_borrow_is_returned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='book_module.book'),
        ),
    ]
