# Generated by Django 5.2.4 on 2025-07-16 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='نام')),
                ('last_name', models.CharField(max_length=200, verbose_name='نام خانوادگی')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('nationality', models.CharField(max_length=200, verbose_name='ملیت')),
                ('date_of_birth', models.DateField(verbose_name='تاریخ تولد')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسنده ها',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'ناشر',
                'verbose_name_plural': 'ناشر ها',
            },
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='نام')),
                ('last_name', models.CharField(max_length=200, verbose_name='نام خانوادگی')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'مترجم',
                'verbose_name_plural': 'مترجم ها',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان')),
                ('url_title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان در url')),
                ('page', models.PositiveIntegerField(verbose_name='صفحه')),
                ('min_age', models.PositiveIntegerField(verbose_name='حداقل سن')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='book_module.author', verbose_name='مترجم')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='book_module.publisher', verbose_name='ناشر')),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translator', to='book_module.translator', verbose_name='مترجم')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب ها',
            },
        ),
    ]
