# Generated by Django 5.2.4 on 2025-07-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد'),
        ),
    ]
