# Generated by Django 5.2.4 on 2025-07-17 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_module', '0002_book_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='release_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ عرضه'),
            preserve_default=False,
        ),
    ]
