# Generated by Django 5.2.4 on 2025-07-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_module', '0003_book_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products', verbose_name='تصویر کتاب'),
        ),
    ]
