# Generated by Django 5.2.4 on 2025-07-18 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_module', '0007_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='url_title',
        ),
    ]
