# Generated by Django 5.2.4 on 2025-07-23 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_module', '0008_remove_book_url_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام کشور')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='نام در url')),
            ],
            options={
                'verbose_name': 'کشور',
                'verbose_name_plural': 'کشور ها',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='url_title',
            field=models.CharField(db_index=True, default='test', max_length=300, verbose_name='نام در url'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='url_title',
            field=models.CharField(db_index=True, default='test', max_length=300, verbose_name='نام در url'),
        ),
        migrations.AddField(
            model_name='translator',
            name='url_title',
            field=models.CharField(db_index=True, default='test', max_length=300, verbose_name='نام در url'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='book_module.author', verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='author',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_module.nationality', verbose_name='ملیت'),
        ),
    ]
