# Generated by Django 5.2.4 on 2025-08-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_module', '0010_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationality',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100, unique=True, verbose_name='نام در url'),
        ),
    ]
