# Generated by Django 5.2.4 on 2025-08-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_module', '0011_alter_nationality_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='url_title',
            field=models.CharField(blank=True, db_index=True, default='', max_length=300, verbose_name='نام در url'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='url_title',
            field=models.CharField(blank=True, db_index=True, default='test', max_length=300, verbose_name='نام در url'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='url_title',
            field=models.CharField(blank=True, db_index=True, default='', max_length=300, verbose_name='نام در url'),
        ),
    ]
