# Generated by Django 5.2.4 on 2025-08-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_module', '0012_alter_author_url_title_alter_publisher_url_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='url_title',
            field=models.SlugField(allow_unicode=True, blank=True, default='', max_length=300, verbose_name='نام در url'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', max_length=200, unique=True, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', max_length=100, unique=True, verbose_name='نام در url'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='url_title',
            field=models.SlugField(allow_unicode=True, blank=True, default='test', max_length=300, verbose_name='نام در url'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='url_title',
            field=models.SlugField(allow_unicode=True, blank=True, default='', max_length=300, verbose_name='نام در url'),
        ),
    ]
