# Generated by Django 5.2.4 on 2025-08-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_module', '0013_alter_author_url_title_alter_book_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='url_title',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=300, verbose_name='نام در url'),
        ),
    ]
