# Generated by Django 5.2.4 on 2025-08-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_module', '0014_alter_book_slug_alter_publisher_url_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='date_of_birth',
        ),
    ]
